### ISSUE TITLE
Python 3 support [moved]

### ISSUE THREAD

**Issue by trentm** [trentm/cmdln#24]
This is [Issue 24](http://code.google.com/p/cmdln/issues/detail?id=24) moved from a Google Code project.
Added by 2010-04-28T20:51:24.000Z by [Sridhar....@gmail.com](http://code.google.com/u/107514687808578919461/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Task, Priority-Medium

### Original description

    is now implemented in ^/branches/cfg: http://code.google.com/p/cmdln/source/detail?r=79

**Comment by stuaxo** [comment]
I guess the branch didn't survive the move..  I started porting to python3 again

https://github.com/trentm/cmdln/pull/32

**Comment by trentm** [comment]
great, thanks
